// AUTO-GENERATED by scripts/gen-colours-types.js — do not edit by hand.
// Regenerate after changing colour keys: node scripts/gen-colours-types.js

type ColourKey =
  | 'ERROR';

/** Flat colour-theme map: every dot-namespaced key resolves to the active-theme colour value. */
declare const colours: Record<ColourKey, string>;
