// AUTO-GENERATED by scripts/gen-l10n-types.js — do not edit by hand.
// Regenerate after changing localization keys: node scripts/gen-l10n-types.js

type L10nKey =
  | 'cartPage'
  | 'checkoutCompletePage'
  | 'checkoutOverviewPage'
  | 'checkoutPage'
  | 'footer'
  | 'header'
  | 'inventoryPage'
  | 'loginPage';

/** Flat localization map: every dot-namespaced key resolves to the active-language string. */
declare const l10n: Record<L10nKey, string>;
